project:
  type: website

website:
  title: "FrenchKrab"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        icon: file-person
        text: About
      - href: blog.qmd
        icon: journal-text
        text: Blog

format:
  html:
    mermaid:
      theme: default
    theme:
      light: united
    css: styles.css
    toc: true


